version: "3.7"

services: 
    database_ignite:
        image: mysql
        container_name: brickup_database
        restart: always
        ports: 
            - "3306:3306"
        environment:
            - POSTGRES_USER=brickup
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=schedulings
        volumes:
            - mysqldata:/data/mysql
        # network_mode: host
        
    # app:
    #     build: .
    #     container_name: brickup_database
    #     ports:
    #         - "3333:3333"
    #     volumes:
    #         - .:/usr/app
    # network_mode: host


volumes:
    pgdata:
        driver: local
